DECLARE @EMP_NAME varchar(100);
DECLARE @EMP_ID int;
DECLARE @EMP_DOB date;
DECLARE @EMP_ADDRESS varchar(100);

DECLARE @BRANCH_IFSC VARCHAR(11);
DECLARE @BRANCH_NAME VARCHAR(100);
DECLARE @BRANCH_ADDRESS VARCHAR(100);

DECLARE @CUST_ID VARCHAR(20);
DECLARE @CUST_NAME VARCHAR(100);
DECLARE @CUST_DOB DATE;
DECLARE @CUST_PHONE VARCHAR(20);
DECLARE @CUST_ADDRESS VARCHAR(100);

DECLARE @ACT_BAL FLOAT;
DECLARE @ACT_TYPE VARCHAR(50);
DECLARE @ACT_CUSTID VARCHAR(20);
DECLARE @ACT_NUM varchar(12);

DECLARE @tran_amt float;
declare @tran_id varchar(50);
declare @tran_type varchar(20);
declare @tran_time datetime;

SET @EMP_NAME = 'AKSHATHA';
SET @EMP_ID = '4314';
SET @EMP_DOB = '2001-09-29';
SET @EMP_ADDRESS = 'Sri Kripa H.No:10/32G-G1 manipal, udupi 57625, Karnataka';

SET @BRANCH_IFSC = 'CNRB00001024'
SET @BRANCH_NAME = 'UDUPI'
SET @BRANCH_ADDRESS = 'CANARA BANK, opposite to mandavi prince, mg road, mangaluru-576215';

SET @CUST_ID = '23456788'
SET @CUST_NAME = 'Supriya shenoy udyavara'
SET @CUST_DOB = '2001-04-29';
SET @CUST_PHONE = '1234567891'
SET @CUST_ADDRESS = 'supriya kripa, opposite to canarabank, udyavar, 543678';

SET @ACT_BAL = 300000;
SET @ACT_TYPE ='savings';
SET @ACT_NUM = '123456789012'; 

set @tran_amt = 12000;
set @tran_id = 'TR234RRT55';
set @tran_type = 'online';
set @tran_time = '12-09-2023';



PRINT @BRANCH_IFSC;
PRINT @BRANCH_NAME; 
PRINT  @BRANCH_ADDRESS;

PRINT @EMP_NAME;
PRINT @EMP_ID;
PRINT @EMP_DOB;
PRINT @EMP_ADDRESS;

PRINT @CUST_ID 
PRINT @CUST_NAME
PRINT @CUST_DOB
PRINT @CUST_PHONE
PRINT @CUST_ADDRESS;

PRINT @ACT_BAL;
PRINT @ACT_TYPE
PRINT @ACT_NUM ;

PRINT @tran_amt;
PRINT @tran_id;
PRINT @tran_type;
PRINT @tran_time;